# This Dockerfile.dockerignore file is located in the docker/ folder for better organization.
# A symlink at the repository root (Dockerfile.dockerignore -> docker/Dockerfile.dockerignore) allows
# Docker to find it when building with the root directory as the build context.
# See: https://stackoverflow.com/questions/28097064/dockerignore-ignore-everything-except-a-file-and-the-dockerfile

# Ignore Everything
**

# but don't ignore those files/folders
!go.mod
!go.sum
!README.md
!cmd/
!pkg/
!internal/

# In those folders make sure those files are not included
**/.git
**/node_modules
**/.venv
**/bin
**/dist
**/.cache
